const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k){try{return localStorage.getItem(k)}catch(e){return null}},set(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}};
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.classList.remove('show'),2600)}
function toggleTheme(){document.body.classList.toggle('light');store.set('theme',document.body.classList.contains('light')?'light':'dark')}
if(store.get('theme')==='light')document.body.classList.add('light');
$('#themeBtn')?.addEventListener('click',toggleTheme);
function unlock(n){const cur=Number(store.get('unlocked')||1);if(n>cur)store.set('unlocked',String(n))}
const pg=Number(document.body.dataset.page||1);unlock(pg);$$('[data-next]').forEach(a=>a.addEventListener('click',()=>unlock(Number(a.dataset.next))));
function tick(){const start=new Date('2026-01-04T00:00:00-03:00');const now=new Date();let d=Math.max(0,now-start);const days=Math.floor(d/864e5);d%=864e5;const h=Math.floor(d/36e5);d%=36e5;const m=Math.floor(d/6e4);const s=Math.floor((d%6e4)/1000);$('#days')&&( $('#days').textContent=days,$('#hours').textContent=String(h).padStart(2,'0'),$('#mins').textContent=String(m).padStart(2,'0'),$('#secs').textContent=String(s).padStart(2,'0'))}tick();setInterval(tick,1000);
const audio=$('#song');const play=$('#playSong');const fill=$('#songFill');if(audio&&play){play.addEventListener('click',async()=>{try{if(audio.paused){await audio.play();play.textContent='❚❚'}else{audio.pause();play.textContent='▶'}}catch(e){toast('Toque novamente para iniciar a música ♡')}});audio.addEventListener('timeupdate',()=>{if(audio.duration&&fill)fill.style.width=(audio.currentTime/audio.duration*100)+'%'});audio.addEventListener('ended',()=>play.textContent='▶')}
const photoInput=$('#photoInput'),customPreview=$('#customPreview'),customPlaceholder=$('#customPlaceholder');function showCustom(src){if(!customPreview)return;customPreview.src=src;customPreview.style.display='block';customPlaceholder&&(customPlaceholder.style.display='none')}const saved=store.get('customPhoto');if(saved)showCustom(saved);photoInput?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return toast('Escolha uma foto válida.');if(f.size>10*1024*1024)return toast('Use uma foto de até 10 MB.');const r=new FileReader();r.onload=()=>{showCustom(r.result);const ok=store.set('customPhoto',r.result);toast(ok?'Foto colocada e salva neste aparelho ♡':'Foto colocada ♡ (sem salvar permanentemente)')};r.onerror=()=>toast('Não consegui abrir essa foto.');r.readAsDataURL(f)});
$$('.secret').forEach(card=>{$('.secret-cover',card)?.addEventListener('click',e=>{if(e.target.closest('button,input'))return;card.classList.toggle('open')});$('.revealSecret',card)?.addEventListener('click',()=>{card.classList.add('open');const input=$('input',card);if(input?.value.trim())toast('Gostei do seu palpite ♡')})});
$('#replyBtn')?.addEventListener('click',()=>{const v=$('#journal')?.value.trim();const out=$('#reply');if(!out)return;out.textContent=v?`Eu li o que você escreveu. Não precisa resolver tudo agora. O que você sente merece espaço, carinho e respeito. Eu quero continuar aqui para ouvir, sem te pressionar. ♡`:'Mesmo sem escrever nada, você pode ficar aqui um pouquinho. Esse espaço também é seu. ♡';out.classList.add('show')});
const symbols=['♡','☾','✦','🌷','🫶','💌'];let picks=[],lock=false,matches=0;const game=$('#game');if(game){const deck=[...symbols,...symbols].sort(()=>Math.random()-.5);deck.forEach((x,i)=>{const b=document.createElement('button');b.className='tile';b.dataset.v=x;b.innerHTML=`<span>${x}</span>`;b.addEventListener('click',()=>{if(lock||b.classList.contains('done')||b.classList.contains('open'))return;b.classList.add('open');picks.push(b);if(picks.length===2){lock=true;setTimeout(()=>{if(picks[0].dataset.v===picks[1].dataset.v){picks.forEach(x=>x.classList.add('done'));matches++;if(matches===symbols.length){toast('Você encontrou todos ♡');burst(95)}}else picks.forEach(x=>x.classList.remove('open'));picks=[];lock=false},650)}});game.appendChild(b)})}
const phases=[
['Fase 1 — O começo','Desde 04/01/2026 existe um “nós” que eu guardo com muito carinho. Não porque tudo seja perfeito, mas porque foi com você que eu quis viver cada detalhe, cada conversa e cada reencontro.'],
['Fase 2 — Os dias difíceis','Eu sei que existem cansaços, estresses e momentos em que parece mais fácil se fechar. Eu não quero transformar amor em cobrança. Quero aprender a ser alguém com quem você possa respirar, falar e também ficar em silêncio quando precisar.'],
['Fase 3 — O que eu escolho','Eu escolho continuar cuidando do que é nosso com atitude, respeito e paciência. Quero que as minhas palavras tenham companhia: presença, mudança quando eu errar e carinho sem pressão.'],
['Fase 4 — Para você, Gaby','Mais um mês passou, e eu ainda quero descobrir muitos capítulos ao seu lado. Obrigado pelos momentos, pelas tentativas e por tudo que ainda estamos construindo. Eu te amo. Feliz aniversário de namoro. ♡']];
let phase=Number(store.get('letterPhase')||0);function drawPhase(){const t=$('#letterTitle'),p=$('#letterText');if(!t||!p)return;t.textContent=phases[phase][0];p.textContent=phases[phase][1];$$('.dots i').forEach((d,i)=>d.classList.toggle('on',i===phase));$('#prevPhase')&&( $('#prevPhase').disabled=phase===0);$('#nextPhase')&&( $('#nextPhase').textContent=phase===phases.length-1?'Ir para a surpresa final →':'Revelar próxima fase →')}drawPhase();$('#prevPhase')?.addEventListener('click',()=>{if(phase>0){phase--;store.set('letterPhase',phase);drawPhase()}});$('#nextPhase')?.addEventListener('click',()=>{if(phase<phases.length-1){phase++;store.set('letterPhase',phase);drawPhase();burst(28)}else{unlock(8);location.href='final.html'}});
function burst(n=120){const host=$('#heartLayer');if(!host)return;for(let i=0;i<n;i++){setTimeout(()=>{const h=document.createElement('span');h.className='heartBurst';h.textContent=Math.random()>.35?'♡':'♥';h.style.left=(Math.random()*100)+'vw';h.style.setProperty('--s',(14+Math.random()*34)+'px');h.style.setProperty('--d',(3.4+Math.random()*3.2)+'s');h.style.color=Math.random()>.5?'#ff8fbd':'#c6a9ff';host.appendChild(h);setTimeout(()=>h.remove(),7000)},i*18)}}
$('#burstBtn')?.addEventListener('click',()=>burst(180));$('#finalReveal')?.addEventListener('click',()=>{$('#finalMessage')?.classList.add('show');burst(220)});
